#!/bin/bash

# Silence it for now. When we run this script we only want the now output.
scripts/build > /dev/null

cd build

echo '{
  "name": "decode-studio-web"
}' > now.json

now --public

rm now.json
