#!/bin/bash

export NODE_ENV=development

rm -rf ./src/node/desktop/build
rm -rf ./src/dom/desktop/build

$(npm bin)/webpack --config ./configs/webpack/desktop-main.js
$(npm bin)/webpack --config ./configs/webpack/desktop-renderer.js

$(npm bin)/concurrently \
  "$(npm bin)/electron ./src/node/desktop/build/bundle.js" \
  "$(npm bin)/webpack --config ./configs/webpack/desktop-renderer.js --watch"
