#!/bin/bash

# This script should be idempotent! In other words you should be able to run it
# multiple times and you will always get the same result no matter the previous
# state of universe.

echo ""
echo "[1/1] Bootstrapping with lerna."
echo ""
$(npm bin)/lerna bootstrap
