#!/bin/bash

# This script should be idempotent! In other words you should be able to run it
# multiple times and you will always get the same result no matter the previous
# state of universe.

echo ""
echo "[1/2] Cleaning existing node_modules."
rm -rf node_modules
rm -rf packages/*/node_modules

echo ""
echo "[2/2] Installing node_modules with yarn."
echo ""
yarn

echo ""
