#!/bin/bash

scripts/build

cd build

echo '{
  "name": "decode-studio-signal-server",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "socket.io": "^1.7.3"
  }
}' > package.json

now --public

rm package.json
