#!/bin/bash

export NODE_ENV=development

$(npm bin)/concurrently \
  '$(npm bin)/webpack-dev-server --config ./webpack.config.renderer.js --port 1998' \
  '$(npm bin)/tsc --project ./tsconfig.main.json && $(npm bin)/electron .'
