#!/bin/bash

export NODE_ENV=development

$(npm bin)/concurrently \
  '$(npm bin)/webpack --config ./webpack.config.renderer.js --watch' \
  '$(npm bin)/tsc --project ./tsconfig.main.json && $(npm bin)/electron .'
