#!/bin/bash

# Get the path to the TypeScript binary we will use.
tsc=$(npm bin)/tsc

# Get the base directory. This is the current working directory most often.
base_directory=$(pwd)

# Get all of the tsconfig.json files that we can find excluding those in
# node_modules packages. We will consider all of these tsconfig.json files to
# represent a TypeScript enabled directory.
tsconfig_paths=$(find $base_directory -name 'tsconfig.json' -not -path '*/node_modules/*')

# Loop through all of the TypeScript paths.
for tsconfig_path in $tsconfig_paths; do
  # Go to the directory which holds the TypeScript config.
  cd $(dirname $tsconfig_path)
  # Log the directory we are checking relative to our base directory.
  node -e "const path = require('path'); console.log('🔦  Checking', './' + path.relative('$base_directory', '$(pwd)'));"
  # Actually run TypeScript. We expect that there is an installed TypeScript
  # package in the node_modules for this directory.
  $tsc
  # Go back to the base directory.
  cd $base_directory
done
